config/routes.rb
Socal::Application.routes.draw do
  root to: "socals#index"
  resources :commands
  resources :songs
end

app/models/command.rb
class Command < ActiveRecord::Base
	attr_accessible :phrase
	validates :phrase, presence: true, uniqueness: true

	def remove_special_characters
		self.phrase.gsub(/[^0-9A-Za-z]/, ' ').squeeze(" ").strip
	end

	def phrase_to_api_sound
		phrase = self.remove_special_characters.gsub(" ", "+")
		phrase = "http://tts-api.com/tts.mp3?q=#{phrase}"
	end
end

app/models/song.rb
class Song < ActiveRecord::Base
	attr_accessible :artist, :title, :audio_file
	mount_uploader :audio_file, SongUploader

	validates :audio_file, presence: true
	validates :title, presence: true
	validates :artist, presence: true

	def store_dir
    	"uploads/song/audio_file/#{self.id}"
  	end

  	def previous_song
  		Song.limit(1).order("id DESC").where("id < ?", id).first
	end

	def next_song
  		Song.limit(1).order("id ASC").where("id > ?", id).first
	end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  config.generators do |g|
    g.test_framework :rspec, fixture: true
    g.fixture_replacement :factory_girl, dir: 'spec/factories'
    g.view_specs false
    g.helper_specs false
    g.stylesheets = false
    g.javascripts = false
    g.helper = false
  end
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
	def index 
		@commands = Command.page(params[:page]).per(10) 
	end

	def new
		@command = Command.new
	end

	def create 
		@command = Command.new(params[:command])
		if @command.save 
			flash[:notice] = "Command created successfully"
			redirect_to @command
		else
			render :new
		end
	end

	def edit 
		@command = Command.find(params[:id])
	end

	def update 
		@command = Command.find(params[:id])
		if @command.update_attributes(params[:command])
			flash[:notice] = "Command successfully updated"
			redirect_to @command
		else
			render :edit
		end
	end

	def show
		@command = Command.find(params[:id])
	end
end

app/controllers/socals_controller.rb
class SocalsController < ApplicationController
	def index 
		offset = rand(Song.count)
		@song = Song.first(:offset => offset)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	def index 
		@songs = Song.page(params[:page]).per(5) 
	end

	def new 
		@song = Song.new
	end

	def create 
		@song = Song.new(params[:song])
		if @song.save 
			flash[:notice] = "Song saved successfully"
			redirect_to @song
		else
			render :edit
		end
	end

	def show
		@song = Song.find(params[:id])
	end

	def edit 
		@song = Song.find(params[:id])
	end

	def update
		@song = Song.find(params[:id])
		if @song.update_attributes(params[:song])
			flash[:notice] = "Songs successfully updated"
			redirect_to @song
		else
			render :edit
		end 

	end

	def destroy 
		@song = Song.find(params[:id])
		if @song.delete
			flash[:notice] = "Song deleted successfully"
			redirect_to @song
		else
			render :show
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
	def initialize_sound_manager
  	render :partial => "shared/sound_manager"
  end
end

app/helpers/socals_helper.rb
module SocalsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/commands/_form.html.erb
<%= initialize_sound_manager %>


<%= form_for @command do |f| %> 
	<div><%= f.label :phrase %> </div>
	<div><%= f.text_area :phrase %></div>
	<div id="play_command" class="btn btn-primary">Play Command</div>
	<%= f.submit "Save", class: "btn btn-primary" %> 
<% end %> 

app/views/commands/edit.html.erb
<%= render "form" %>

app/views/commands/index.html.erb
<table class="table table-bordered table-striped size_table"> 
<tr>
<th><%= t "command" %></th><th> Edit</th>
</tr> 
<% if @commands.present? %>
	<% @commands.each do |command| %> 
		<tr id="command_<%= command.id %>" class="command_line">
			<td><%= command.phrase %></td>
			<td><%= link_to image_tag("/assets/editbutton.png"), edit_command_path(command), class: "smaller_image" %></td>
		</tr>
	<% end %> 
<% else %> 
	<tr><td>No commands found</td><td></td><tr>
<% end %> 

</table>

<div class="paging_section"> 
	<%= paginate @commands %> 
</div>

<div class="button_section">
<%= link_to "Add New Command", new_command_path, class: "btn btn-primary" %>
</div>

app/views/commands/new.html.erb
<%= form_for @command do |f| %> 
	<div><%= f.label :phrase %> </div>
	<div><%= f.text_area :phrase %></div>

	<%= f.submit "Save" %> 
<% end %> 

app/views/commands/show.html.erb
<% if flash[:notice] %>
  <p class="notice">Command created successfully</p>
<% end %>


<div class="phrase">
	<%= @command.phrase %> 
</div>

<div class="actions">  
<%= link_to "Edit", edit_command_path(@command) %> 
<%#= link_to "Delete", video_path(@video), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
		<div class="navbar-inner">
			<a class="brand" href="/">SOCAL</a>
			<ul class="nav">
				<li><%= link_to "Commands",  commands_path %></li>
				<li><%= link_to "Songs",  songs_path %></li>
			</ul>

		</div>


	</div>
	<%= yield %>

</body>
</html>

app/views/shared/_sound_manager.html.erb
<%= javascript_include_tag "soundmanager/script/soundmanager2.js" %>
<script>

soundManager.setup({
  url: '/swf/',
  // optional: use 100% HTML5 mode where available
  // preferFlash: false,
  onready: function() {
    var mySound = soundManager.createSound({
      id: 'aSound',
      url: '<%= @command.phrase_to_api_sound %>'
    });

    $("#play_command").click(function(){
		    mySound.play(); 
	   });
  },
  ontimeout: function() {
    // Hrmm, SM2 could not start. Missing SWF? Flash blocked? Show an error, etc.?
  }
});



</script>

app/views/socals/index.html.erb
<div> 
	<h1><%= t "welcome" %></h1>
    <li><h3><%= link_to "Commands", commands_path %></h3></li>
     <li><h3><%= link_to "Songs", songs_path %></h3></li>

     <% if @song.present? %> 
     	<%= render "/songs/show" %>  
     <% end %> 
</div>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %> 
	<div><%= f.label :artist %> </div>
	<div><%= f.text_field :artist %></div>

	<div><%= f.label :title %> </div>
	<div><%= f.text_field :title %></div>

	<div><%= f.label :upload_song %></div>
	<div><%= f.file_field :audio_file %></div>

	<%= f.submit "Save" %> 
<% end %> 

app/views/songs/_show.html.erb
<%= javascript_include_tag "soundmanager/script/soundmanager2", "soundmanager/script/berniecode-animator", "soundmanager/script/360player"  %>
<%= stylesheet_link_tag "flashblock", "360player", "360player-visualization" %>

<div class="song_information">
  <div><h1><%= @song.artist %></h1></div>
  <div><h2><%= @song.title %></h2> </div>
</div>

<div class="song_section"> 
  <div class="ui360 ui360-vis song_player">
    <a href="<%= @song.audio_file %>"></a>
  </div> 
</div>

<script type="text/javascript">

soundManager.setup({
  // path to directory containing SM2 SWF
  url: '../../swf/'
});

threeSixtyPlayer.config.scaleFont = (navigator.userAgent.match(/msie/i)?false:true);
threeSixtyPlayer.config.showHMSTime = true;

// enable some spectrum stuffs

threeSixtyPlayer.config.useWaveformData = true;
threeSixtyPlayer.config.useEQData = true;

// enable this in SM2 as well, as needed

if (threeSixtyPlayer.config.useWaveformData) {
  soundManager.flash9Options.useWaveformData = true;
}
if (threeSixtyPlayer.config.useEQData) {
  soundManager.flash9Options.useEQData = true;
}
if (threeSixtyPlayer.config.usePeakData) {
  soundManager.flash9Options.usePeakData = true;
}

if (threeSixtyPlayer.config.useWaveformData || threeSixtyPlayer.flash9Options.useEQData || threeSixtyPlayer.flash9Options.usePeakData) {
  // even if HTML5 supports MP3, prefer flash so the visualization features can be used.
  soundManager.preferFlash = true;
}

// favicon is expensive CPU-wise, but can be enabled.
threeSixtyPlayer.config.useFavIcon = false;

</script>

app/views/songs/edit.html.erb
<%= render "form" %>

app/views/songs/index.html.erb
<%= stylesheet_link_tag "flashblock", "page-player" %>
<%= javascript_include_tag "soundmanager/script/soundmanager2", "soundmanager/script/page-player"  %>
<script type="text/javascript">

soundManager.setup({
  url: '../../swf/'
});

function setTheme(sTheme) {
  var o = document.getElementsByTagName('ul')[0];
  o.className = 'playlist'+(sTheme?' '+sTheme:'');
  return false;
}
</script>

<style type="text/css">

div#containerDiv{
width:300px;
height:50px;
}

.row1 {float:left; width:100px; height:25px;}
.row2 {float:left; width:100px; height:25px;}
</style>

<table class="table table-bordered table-striped size_table">
	<% @songs.each do |song| %> 
		 <tr>
		 	<td><h3><%= song.artist %> - <%= song.title %><h3></td>
		 	<td><%= link_to image_tag("/assets/playbutton.png"), song, class: "smaller_image" %></td> 
		 	<td><%= link_to image_tag("/assets/editbutton.png"), edit_song_path(song), class: "smaller_image" %></td>
		 </tr>
	<% end %> 
</table>

<div class="paging_section"> 
	<%= paginate @songs %> 
</div>

<div class="button_section">
	<%= link_to "Add New Song", new_song_path, class: "btn btn-primary"%>
</div>

app/views/songs/new.html.erb
<%= render "form" %>

app/views/songs/show.html.erb
<%= javascript_include_tag "soundmanager/script/soundmanager2", "soundmanager/script/berniecode-animator", "soundmanager/script/360player"  %>
<%= stylesheet_link_tag "flashblock", "360player", "360player-visualization" %>
<% if flash[:notice] %>
  <p class="notice">Song created successfully</p>
<% end %>



<div class="song_information">
  <div><h1><%= @song.artist %></h1></div>
  <div><h2><%= @song.title %></h2> </div>
</div>


<div class="song_section"> 
  <div class="previous_song">
    <% if @song.previous_song.present? %>
      <%= link_to image_tag("/assets/previous.png"), "/songs/#{@song.previous_song.id}" , id: "previous_button", class: "previous_song" %> 
    <% end %> 
  </div>


  <div class="ui360 ui360-vis song_player">
    <a href="<%= @song.audio_file %>"></a>
     <div class="next_song">
      <% if @song.next_song.present? %>
        <%= link_to image_tag("/assets/next.png"), "/songs/#{@song.next_song.id}" , id: "next_button", class: "next_song" %> 
      <% end %> 
      <%#= image_tag "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/256/Actions-media-seek-forward-icon.png" %> 
    </div>
  </div>

 
</div>



<script type="text/javascript">

soundManager.setup({
  // path to directory containing SM2 SWF
  url: '../../swf/'
});

threeSixtyPlayer.config.scaleFont = (navigator.userAgent.match(/msie/i)?false:true);
threeSixtyPlayer.config.showHMSTime = true;

// enable some spectrum stuffs

threeSixtyPlayer.config.useWaveformData = true;
threeSixtyPlayer.config.useEQData = true;

// enable this in SM2 as well, as needed

if (threeSixtyPlayer.config.useWaveformData) {
  soundManager.flash9Options.useWaveformData = true;
}
if (threeSixtyPlayer.config.useEQData) {
  soundManager.flash9Options.useEQData = true;
}
if (threeSixtyPlayer.config.usePeakData) {
  soundManager.flash9Options.usePeakData = true;
}

if (threeSixtyPlayer.config.useWaveformData || threeSixtyPlayer.flash9Options.useEQData || threeSixtyPlayer.flash9Options.usePeakData) {
  // even if HTML5 supports MP3, prefer flash so the visualization features can be used.
  soundManager.preferFlash = true;
}

// favicon is expensive CPU-wise, but can be enabled.
threeSixtyPlayer.config.useFavIcon = false;

</script>